name: Compile Examples

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: ["esp32:esp32:esp32c3", "esp8266:esp8266:nodemcuv2"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install Platforms
        run: |
          # Tambahkan URL tambahan untuk ESP32 dan ESP8266
          arduino-cli core update-index --additional-urls https://arduino.esp8266.com/stable/package_esp8266com_index.json,https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          
          # Install ESP32
          arduino-cli core install esp32:esp32
          
          # Install ESP8266 (Sekarang index-nya sudah terdaftar)
          arduino-cli core install esp8266:esp8266

      - name: Install IskakINO Dependencies
        run: |
          # Perintah untuk install 4 library Anda via git
          cd $HOME/Arduino/libraries
          git clone https://github.com/iskakfatoni/IskakINO_ArduFast
          git clone https://github.com/iskakfatoni/IskakINO_WifiPortal
          git clone https://github.com/iskakfatoni/IskakINO_FastNTP
          git clone https://github.com/iskakfatoni/IskakINO_LiquidCrystal_I2C

      - name: Compile Example
        run: |
          arduino-cli compile --fqbn ${{ matrix.board }} ./examples/01_SmartFitting/01_SmartFitting.ino
